### ISSUE TITLE
Plugin is not Webpack compatible

### ISSUE THREAD

**Issue by NickIliev** [roblav96/nativescript-onesignal#12]
Change the [main entry ](https://github.com/roblav96/nativescript-onesignal/blob/master/package.json#L5) from `onesignal.js` to `onesignal`

Related to [this](http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html#referencing-platform-specific-modules-from-packagejson) and reported by plugin's client [here](https://stackoverflow.com/questions/44435509/nativescript-angular-webpack-onesignal-plugin?noredirect=1#comment75876669_44435509)

@roblav96 ^^^

**Comment by roblav96** [comment]
@NickIliev All done =]
