### ISSUE TITLE
Android 8.0 - no push notification

### ISSUE THREAD

**Issue by fabio87dea** [roblav96/nativescript-onesignal#25]
With Android 8.0 doesn't working the push notification

**Comment by Ericky14** [comment]
Any update on this issue?

**Comment by jkasten2** [comment]
@fabio87dea I recommend providing more details such as build errors and logcat entires related to the issue to help debug.

**Comment by Ericky14** [comment]
@jkasten2 For me, there's no build errors. It simply doesn't work with android 8.0.

I believe it might be an issue with dependencies. On the OneSignal dashboard, the android 8.0 users have a warning saying "Outdated Android Support Library". But I have no idea which libraries are outdated and how to add them to my project. I tried adding all the ones I could find using methods such as
```
dependencies {
  implementation "com.android.support:..."
}
```
But it still did not work for me.

**Comment by thematan** [comment]
Oreo introduced new notifications API.
you should prepare for it.
here are some docs:
[one signal android categories](https://documentation.onesignal.com/docs/categories)

**Comment by jkasten2** [comment]
This SDK has been updated to support Android Oreo (8.0). Please open a new issue if there is anything related to Oreo you are still seeing.
