### ISSUE TITLE
Please, can someone help changing TS code to JS for NS Core ?

### ISSUE THREAD

**Issue by MopheusDG** [roblav96/nativescript-onesignal#43]
I'm trying to implement the main.ts code into my NS Core JS app to support IOS and Android. I was able to easily change the Android code to JS but IOS one is more challenging, can someone help me switch it to JS please ?

This is the code in the Library TS example:

MAIN.TS (For IOS)
```
import * as application from 'application';
var TnsOneSignal = require('nativescript-onesignal').TnsOneSignal

if (application.ios) {
    class MyDelegate extends UIResponder implements UIApplicationDelegate {
        public static ObjCProtocols = [UIApplicationDelegate]
        private applicationDidFinishLaunchingWithOptions(app: UIApplication, launchOptions: NSDictionary): boolean {
            try {
                console.dump('TnsOneSignal', TnsOneSignal)
                TnsOneSignal.initWithLaunchOptionsAppId(launchOptions, 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba')
            } catch (error) {
                console.error('error', error)
            }
            return true
        }
    }
    application.ios.delegate = MyDelegate
}
```

I think it could be nice to include JS in the docs for futher references, right ?

Also, here's my JS converted for ANDROID, if someone can check it too just in case.... but so far it works.

APP.JS (For ANDROID - Modified)
```
var TnsOneSignal = require("nativescript-onesignal").TnsOneSignal;

if (application.android) {
    application.on(application.launchEvent, function(args) {
        try {
            console.log('TnsOneSignal', TnsOneSignal);
            TnsOneSignal.startInit(application.android.context).init();
        } catch (error) {
            console.log('error', error);
        }
    })
}
```

**Comment by delanick** [comment]
+1

**Comment by ghost** [comment]
Hi MopheusDG

  At this moment i´m stuck with the code for javascript too....and because of that i can´t configure the SDK properly, have you figure it out? could you help me?

Regards

**Comment by MopheusDG** [comment]
Hi @japasanto, you could try (if I'm not wrong) with this TS playground tool that will show you the JS version of any code you type automatically. Typing the code there helped me sometimes to understand what TS was doing, and could/should help you with this case too:

https://www.typescriptlang.org/play/

Hope this helps,
Thanks.

**Comment by ghost** [comment]
Hey MopheusDG

  Thank you for replying, i ended up discovering that link you are giving me, but my VS code was throwing so much "red lines" that i though: this is not going to pass!!!...but it did pass, and the app asked me if it could send me push notifications...ok!..great!...then i went to my onesignal account and i was having an error, a 3000 apns error and it was saying that i should go to my xcode, turn on the push notifications e see the log...well, in nativescript sidekick i was building in the cloud...so...where is my xcode project, i saw the .cloud directory but i didn´t find anything...so i started building locally and now i have acces to myxcode project, fixed the problem and the onesignal account was not complaining anymore...tested with a simple push and it worked.

By the way, have you ever used the onesginal rest api?.

Thanks again for your help, sorry for my bad english and for being so detailed in my answer but maybe someone will have the same problem and this might help.

**Comment by MopheusDG** [comment]
Hi @japasanto glad you worked out ! Unfortunatelly, never used the onesignal rest api, so can't help you on that one.

**Comment by markosole** [comment]
@japasanto I am having same problem and spent all day in implementing this. After success in API keys and not errors in console log, now I need to "run" it. Please can you paste code you ended up with. 

Thanks a lot in advance.

**Comment by markosole** [comment]
Hi guys, I know this is old subject but I need help with TS to JS version. Can you please paste the code that worked for your implementation. I can't make it work, app is crashing when I try to start it.

Thanks in advance.
