### ISSUE TITLE
failed to run npm run build

### ISSUE THREAD

**Issue by ejlocop** [roblav96/nativescript-onesignal#44]
got these errors when I tried to run the demo project.

![image](https://user-images.githubusercontent.com/12082880/46718474-dc22cc80-cc9d-11e8-8fc3-cc857a110b71.png)

here's my npm-log

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle nativescript-onesignal@1.0.8~prebuild: nativescript-onesignal@1.0.8
6 info lifecycle nativescript-onesignal@1.0.8~build: nativescript-onesignal@1.0.8
7 verbose lifecycle nativescript-onesignal@1.0.8~build: unsafe-perm in lifecycle true
8 verbose lifecycle nativescript-onesignal@1.0.8~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Projects\nativescript-onesignal\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\user\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\user\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\user\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\xampp\php;C:\Program Files\MongoDB\Server\4.0\bin;C:\xampp\mysql\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\chocolatey\bin;D:\ProgramFiles\android\android-sdk\tools;D:\ProgramFiles\android\android-sdk\platform-tools;D:\ProgramFiles\Java\jdk-8u181\bin;C:\Program Files\nodejs;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\user\AppData\Roaming\Composer\vendor\bin;C:\Users\user\AppData\Local\Yarn\bin;C:\Users\user\AppData\Roaming\npm
9 verbose lifecycle nativescript-onesignal@1.0.8~build: CWD: D:\Projects\nativescript-onesignal
10 silly lifecycle nativescript-onesignal@1.0.8~build: Args: [ '/d /s /c', 'tsc' ]
11 silly lifecycle nativescript-onesignal@1.0.8~build: Returned: code: 2  signal: null
12 info lifecycle nativescript-onesignal@1.0.8~build: Failed to exec build script
13 verbose stack Error: nativescript-onesignal@1.0.8 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid nativescript-onesignal@1.0.8
15 verbose cwd D:\Projects\nativescript-onesignal
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error nativescript-onesignal@1.0.8 build: `tsc`
22 error Exit status 2
23 error Failed at the nativescript-onesignal@1.0.8 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by mic1983** [comment]
Same problem.
Anyone?
